version: '3.4'

services:
 appdb:
   image: mongo:latest
   networks:
     - app_network

 askme.api:
 # image: ${DOCKER_REGISTRY-}askmeapi
   image: odey114/askme-api:latest
   build:
     context: ..
     dockerfile: AskMe.API/Dockerfile
   networks:
     - app_network

 askme.app:
 # image: ${DOCKER_REGISTRY-}askmeapp
   image: odey114/askme-app:latest
   build:
     context: ..
     dockerfile: AskMe.APP/Dockerfile
   networks:
     - app_network

networks:
 app_network:
   driver: bridge

volumes:
 mongo_data_value: