version: '3.4'

services:
 askme.api:
 #  image: ${DOCKER_REGISTRY-}askme-api
   image: askacr69.azurecr.io/askme-api:latest
 #  image: odey114/askme-api:latest
   build:
     context: ..
     dockerfile: AskMe.API/Dockerfile
   networks:
     - app_network

 askme.app:
 #  image: ${DOCKER_REGISTRY-}askme-app
   image: askacr69.azurecr.io/askme-app:latest
 #  image: odey114/askme-app:latest
   build:
     context: ..
     dockerfile: AskMe.APP/Dockerfile
   networks:
     - app_network

networks:
 app_network:
   driver: bridge

volumes:
 mongo_data_value: