version: '3.4'
##docker-compose -f docker-compose.yml -f docker-compose.override.yml up
##docker tag askme-api:latest odey114/askme-api:latest
##docker tag askme-app:latest odey114/askme-app:latest
##docker push odey114/askme-api:latest
##docker push odey114/askme-app:latest

services:
  askme.api:
    container_name: askme.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "DataBaseSettings:ConnectionString=mongodb://admin:password123@mongodb:27017"
    ports:
      - "8088:80"
      - "4438:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  askme.app:
    container_name: askme.app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "APIConaction=http://host.docker.internal:8088"
    ports:
      - "8089:80"
      - "4439:443"
    depends_on:
      - askme.api
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro