## kubectl apply -f .\nginx-deplyment.yaml
## kubectl delete -f .\nginx-deplyment.yaml
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-depl
  labels:
    app: nginx
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: nginx
  template:
    metadata: 
      name: nginx-depl
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 8090
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
